OUTPUT="$(shell ./Assignment1.sh)";
Assignment1.sh: mystrcat.cpp mystrcat.h mystrlen.cpp mystrlen.h mystrtok.h mystrtok.cpp
	g++ main.cpp mystrcat.cpp mystrcat.h mystrlen.cpp mystrlen.h mystrtok.h mystrtok.cpp -o Assignment1.sh

echo *
